baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Gen AI'


theme = "hugo-theme-m10c"

[params]
  author = "Togay Tunca"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/evinai"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/evinai"